// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRecording(arg1, arg2) {
  return window['go']['facades']['FileSystemStorageFacade']['DeleteRecording'](arg1, arg2);
}

export function GetRecordings(arg1) {
  return window['go']['facades']['FileSystemStorageFacade']['GetRecordings'](arg1);
}

export function RenameLastRecording(arg1) {
  return window['go']['facades']['FileSystemStorageFacade']['RenameLastRecording'](arg1);
}

export function RenameRecording(arg1, arg2, arg3) {
  return window['go']['facades']['FileSystemStorageFacade']['RenameRecording'](arg1, arg2, arg3);
}

export function Save(arg1, arg2) {
  return window['go']['facades']['FileSystemStorageFacade']['Save'](arg1, arg2);
}
