// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort():Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
