// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {interfaces} from '../models';

export function Abort():Promise<void>;

export function Start():Promise<interfaces.StartedResponse>;

export function Stop():Promise<void>;
