// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort() {
  return window['go']['facades']['RecordingFacade']['Abort']();
}

export function Start() {
  return window['go']['facades']['RecordingFacade']['Start']();
}

export function Stop() {
  return window['go']['facades']['RecordingFacade']['Stop']();
}
