// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecordings(arg1) {
  return window['go']['services']['FileSystemStorageService']['GetRecordings'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['services']['FileSystemStorageService']['Save'](arg1, arg2);
}
