// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRecording(arg1, arg2) {
  return window['go']['services']['FileSystemStorageService']['DeleteRecording'](arg1, arg2);
}

export function GetRecordings(arg1) {
  return window['go']['services']['FileSystemStorageService']['GetRecordings'](arg1);
}

export function RenameRecording(arg1, arg2, arg3) {
  return window['go']['services']['FileSystemStorageService']['RenameRecording'](arg1, arg2, arg3);
}

export function Save(arg1, arg2) {
  return window['go']['services']['FileSystemStorageService']['Save'](arg1, arg2);
}
