// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetState():Promise<models.MetronomeStateEventData>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function UpdateBpm(arg1:number):Promise<void>;
