// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['services']['MetronomeService']['GetState']();
}

export function Start() {
  return window['go']['services']['MetronomeService']['Start']();
}

export function Stop() {
  return window['go']['services']['MetronomeService']['Stop']();
}

export function UpdateBpm(arg1) {
  return window['go']['services']['MetronomeService']['UpdateBpm'](arg1);
}
