// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort() {
  return window['go']['services']['RecordingService']['Abort']();
}

export function GetMic() {
  return window['go']['services']['RecordingService']['GetMic']();
}

export function Init() {
  return window['go']['services']['RecordingService']['Init']();
}

export function Start() {
  return window['go']['services']['RecordingService']['Start']();
}

export function Stop() {
  return window['go']['services']['RecordingService']['Stop']();
}
