// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Load():Promise<services.Settings>;

export function Save(arg1:services.Settings):Promise<void>;
