// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load() {
  return window['go']['services']['SettingsService']['Load']();
}

export function Save(arg1) {
  return window['go']['services']['SettingsService']['Save'](arg1);
}
