// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Load():Promise<models.Settings>;

export function Save(arg1:models.Settings):Promise<void>;
