// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function NoOp(arg1:models.RecordingRunningEventData,arg2:models.LiveAudioEventData):Promise<void>;
