// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortRecording() {
  return window['go']['main']['App']['AbortRecording']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
