all: false
dir: "internal/pkg/testutils/mocks"
filename: "{{.InterfaceName | snakecase}}_mock.go"
force-file-write: true
formatter: goimports
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "mocks"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  server/internal/pkg/interfaces:
    config:
      all: true
