// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"server/internal/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type MockEventBus
func (_mock *MockEventBus) Dispatch(event models.EventLike) {
	_mock.Called(event)
	return
}

// MockEventBus_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockEventBus_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - event models.EventLike
func (_e *MockEventBus_Expecter) Dispatch(event interface{}) *MockEventBus_Dispatch_Call {
	return &MockEventBus_Dispatch_Call{Call: _e.mock.On("Dispatch", event)}
}

func (_c *MockEventBus_Dispatch_Call) Run(run func(event models.EventLike)) *MockEventBus_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.EventLike
		if args[0] != nil {
			arg0 = args[0].(models.EventLike)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventBus_Dispatch_Call) Return() *MockEventBus_Dispatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_Dispatch_Call) RunAndReturn(run func(event models.EventLike)) *MockEventBus_Dispatch_Call {
	_c.Run(run)
	return _c
}

// OnEvent provides a mock function for the type MockEventBus
func (_mock *MockEventBus) OnEvent(eventId models.EventId, cb func(any)) {
	_mock.Called(eventId, cb)
	return
}

// MockEventBus_OnEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnEvent'
type MockEventBus_OnEvent_Call struct {
	*mock.Call
}

// OnEvent is a helper method to define mock.On call
//   - eventId models.EventId
//   - cb func(any)
func (_e *MockEventBus_Expecter) OnEvent(eventId interface{}, cb interface{}) *MockEventBus_OnEvent_Call {
	return &MockEventBus_OnEvent_Call{Call: _e.mock.On("OnEvent", eventId, cb)}
}

func (_c *MockEventBus_OnEvent_Call) Run(run func(eventId models.EventId, cb func(any))) *MockEventBus_OnEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.EventId
		if args[0] != nil {
			arg0 = args[0].(models.EventId)
		}
		var arg1 func(any)
		if args[1] != nil {
			arg1 = args[1].(func(any))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventBus_OnEvent_Call) Return() *MockEventBus_OnEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_OnEvent_Call) RunAndReturn(run func(eventId models.EventId, cb func(any))) *MockEventBus_OnEvent_Call {
	_c.Run(run)
	return _c
}
