// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"server/internal/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMetronome creates a new instance of MockMetronome. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetronome(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetronome {
	mock := &MockMetronome{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetronome is an autogenerated mock type for the Metronome type
type MockMetronome struct {
	mock.Mock
}

type MockMetronome_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetronome) EXPECT() *MockMetronome_Expecter {
	return &MockMetronome_Expecter{mock: &_m.Mock}
}

// GetState provides a mock function for the type MockMetronome
func (_mock *MockMetronome) GetState() models.MetronomeStateEventData {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 models.MetronomeStateEventData
	if returnFunc, ok := ret.Get(0).(func() models.MetronomeStateEventData); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(models.MetronomeStateEventData)
	}
	return r0
}

// MockMetronome_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockMetronome_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *MockMetronome_Expecter) GetState() *MockMetronome_GetState_Call {
	return &MockMetronome_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *MockMetronome_GetState_Call) Run(run func()) *MockMetronome_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetronome_GetState_Call) Return(metronomeStateEventData models.MetronomeStateEventData) *MockMetronome_GetState_Call {
	_c.Call.Return(metronomeStateEventData)
	return _c
}

func (_c *MockMetronome_GetState_Call) RunAndReturn(run func() models.MetronomeStateEventData) *MockMetronome_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockMetronome
func (_mock *MockMetronome) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetronome_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockMetronome_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockMetronome_Expecter) Start() *MockMetronome_Start_Call {
	return &MockMetronome_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockMetronome_Start_Call) Run(run func()) *MockMetronome_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetronome_Start_Call) Return(err error) *MockMetronome_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetronome_Start_Call) RunAndReturn(run func() error) *MockMetronome_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockMetronome
func (_mock *MockMetronome) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetronome_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockMetronome_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockMetronome_Expecter) Stop() *MockMetronome_Stop_Call {
	return &MockMetronome_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockMetronome_Stop_Call) Run(run func()) *MockMetronome_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetronome_Stop_Call) Return(err error) *MockMetronome_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetronome_Stop_Call) RunAndReturn(run func() error) *MockMetronome_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBpm provides a mock function for the type MockMetronome
func (_mock *MockMetronome) UpdateBpm(bpm int) error {
	ret := _mock.Called(bpm)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBpm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(bpm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetronome_UpdateBpm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBpm'
type MockMetronome_UpdateBpm_Call struct {
	*mock.Call
}

// UpdateBpm is a helper method to define mock.On call
//   - bpm int
func (_e *MockMetronome_Expecter) UpdateBpm(bpm interface{}) *MockMetronome_UpdateBpm_Call {
	return &MockMetronome_UpdateBpm_Call{Call: _e.mock.On("UpdateBpm", bpm)}
}

func (_c *MockMetronome_UpdateBpm_Call) Run(run func(bpm int)) *MockMetronome_UpdateBpm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetronome_UpdateBpm_Call) Return(err error) *MockMetronome_UpdateBpm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetronome_UpdateBpm_Call) RunAndReturn(run func(bpm int) error) *MockMetronome_UpdateBpm_Call {
	_c.Call.Return(run)
	return _c
}
