// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"server/internal/pkg/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPlaybackService creates a new instance of MockPlaybackService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaybackService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaybackService {
	mock := &MockPlaybackService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlaybackService is an autogenerated mock type for the PlaybackService type
type MockPlaybackService struct {
	mock.Mock
}

type MockPlaybackService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaybackService) EXPECT() *MockPlaybackService_Expecter {
	return &MockPlaybackService_Expecter{mock: &_m.Mock}
}

// Play provides a mock function for the type MockPlaybackService
func (_mock *MockPlaybackService) Play(effect interfaces.AudioEffect) {
	_mock.Called(effect)
	return
}

// MockPlaybackService_Play_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Play'
type MockPlaybackService_Play_Call struct {
	*mock.Call
}

// Play is a helper method to define mock.On call
//   - effect interfaces.AudioEffect
func (_e *MockPlaybackService_Expecter) Play(effect interface{}) *MockPlaybackService_Play_Call {
	return &MockPlaybackService_Play_Call{Call: _e.mock.On("Play", effect)}
}

func (_c *MockPlaybackService_Play_Call) Run(run func(effect interfaces.AudioEffect)) *MockPlaybackService_Play_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interfaces.AudioEffect
		if args[0] != nil {
			arg0 = args[0].(interfaces.AudioEffect)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaybackService_Play_Call) Return() *MockPlaybackService_Play_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlaybackService_Play_Call) RunAndReturn(run func(effect interfaces.AudioEffect)) *MockPlaybackService_Play_Call {
	_c.Run(run)
	return _c
}
